name: AutomergeCron

on:
  # TODO: remove this before merging
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.3'

      - run: cd automerge && go build -o ~/automerge github.com/solana-labs/token-list/automerge

      - run: ~/automerge -v=1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
